- debug: msg="START - agent.yml"

# - name: Write Tokens to File System
#   import_tasks: token-write.yml
#   when:
#     - agent_token_file.stat.exists == false
#     - vault_token_file.stat.exists == false

- name: Add ACL configuration - agent.yml
  template:
    src: etc/consul.d/acl.hcl.j2
    dest: '/etc/consul.d/acl.hcl'
    owner: 'consul'
    group: 'consul'
    mode: 0660

# - name: Replace ACL token placeholder in Consul config
#   lineinfile:
#     path: /etc/consul.d/acl.hcl
#     regexp: "## AGENT_TOKEN_PLACEHOLDER ##"
#     line: "    agent = \"{{ client_agent_token }}\""
#   register: consul_agent_config

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_agent_config.changed

- name: Wait and check for serf port
  wait_for:
    port: "{{ consul_serf_lan_port }}"
    delay: 6

- debug: msg="END - agent.yml"
