- debug: msg="START - agent.yml"

- name: Fetch client agent token from parameter store
  shell: "aws ssm get-parameter --output json --region {{ ansible_ec2_placement_region }} --with-decryption --name consul-{{ consul_join_tag_value }}-acl-client | jq -r '.Parameter | .Value'"
  register: client_agent_token
  until: client_agent_token.stdout != "REPLACEME"
  retries: 120
  delay: 2
  ignore_errors: yes

- name: Add ACL configuration - agent.yml
  template:
    src: etc/consul.d/acl.hcl.j2
    dest: '/etc/consul.d/acl.hcl'
    owner: 'consul'
    group: 'consul'
    mode: 0660

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_agent_config.changed

- name: Wait and check for serf port
  wait_for:
    port: "{{ consul_serf_lan_port }}"
    delay: 6

- debug: msg="END - agent.yml"
