- debug: msg="START - agent.yml"

- name: Add ACL configuration
  template:
    src: etc/consul.d/acl.hcl.j2
    dest: '/etc/consul.d/acl.hcl'
    owner: 'consul'
    group: 'consul'
    mode: 0660

- name: Replace ACL token placeholder in Consul config
  lineinfile:
    path: /etc/consul.d/acl.hcl
    regexp: "## AGENT_TOKEN_PLACEHOLDER ##"
    line: "    agent = \"{{ client_agent_token }}\""
  register: consul_agent_config

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_agent_config.changed

- name: Wait and check for serf port
  wait_for:
    port: "{{ consul_serf_lan_port }}"
    delay: 6

- debug: msg="END - agent.yml"
