- name: Write Consul agent ACL policy
  set_fact:
    agent_policy: |
      agent_prefix "" {
        policy = "write"
      }
      node_prefix "" {
        policy = "write"
      }
      service_prefix "" {
        policy = "read"
      }

- name: Make Consul agent ACL policy machine-readable
  set_fact:
    agent_policy_api_value: "{{
      agent_policy |
        regex_replace('\n', ' ') |
        regex_replace('\"', '\\\"') |
        regex_replace('\\s+', ' ')
    }}"

- name: Write Consul agent ACL policy to Consul
  uri:
    body_format: json
    body: |
      {
        "Name": "{{ consul_agent_policy_name }}",
        "Description": "Consul agent token",
        "Rules": "{{ agent_policy_api_value }}"
      }
    method: PUT
    url: https://127.0.0.1:7501/v1/acl/policy
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    validate_certs: no
  register: consul_agent_token_write
  # until: consul_agent_token_write.status == "200"
  # retries: 120
  # delay: 2

- name: Create agent token
  uri:
    body_format: json
    body: |
      {
        "Description": "Agent token",
        "Policies": [{"Name": "{{ consul_agent_policy_name }}"}],
        "Local": false
      }
    method: PUT
    url: https://127.0.0.1:7501/v1/acl/token
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    validate_certs: no
    return_content: yes
  register: agent_token

- name: Show Agent Token
  debug:
    var: agent_token

- name: Archive ACL agent token
  copy:
    content: "{{ agent_token.json.SecretID }}"
    dest: /etc/consul.d/tokens/agent
    owner: consul
    group: consul
    mode: 0640

- name: Archive ACL agent token to parameter store
  aws_ssm_parameter_store:
    string_type: "SecureString"
    name: "consul-{{ consul_join_tag_value }}-client"
    value: "{{ consul_acl_master_token }}"
    description: "Consul Storage Server client agent ACL token"
    region: "{{ ansible_ec2_placement_region }}"
  run_once: yes
