- name: Gather instance metadata
  ec2_metadata_facts:

- name: adding existing user ec2-user to consul and hashi groups
  user:
    name: 'ec2-user'
    groups: consul
    append: yes

- name: Check for master token
  stat:
    path: /etc/consul.d/tokens/master
  register: master_token_file
  ignore_errors: yes

- name: Check for agent token
  stat:
    path: /etc/consul.d/tokens/agent
  register: agent_token_file
  ignore_errors: yes

- name: Check for vault token
  stat:
    path: /etc/consul.d/tokens/vault
  register: vault_token_file
  ignore_errors: yes

- name: Copy file with owner and permissions
  copy:
    src: "cleanup.sh"
    dest: /bin/cleanup
    owner: root
    group: root
    mode: '0750'

- name: Enable TLS if HTTPS port enabled
  set_fact: consul_tls_enabled="{{ (consul_https_port != -1) | ternary(True, False) }}"

- name: Set API endpoint to HTTP or HTTPS
  set_fact:
    consul_api_protocol: "{{ consul_tls_enabled | ternary('https', 'http') }}"
    consul_api_port: "{{ consul_tls_enabled | ternary(consul_https_port, consul_http_port) }}"

- name: Install CA certificate
  copy:
    src: etc/consul.d/tls/{{ item }}
    dest: /etc/consul.d/tls/{{ item }}
    owner: consul
    group: consul
    mode: 0440
  with_items:
    - consul-agent-ca.pem
  no_log: true

- name: Install client certificate and key
  copy:
    src: "etc/consul.d/tls/{{ item }}"
    dest: "/etc/consul.d/tls/{{ item }}"
    owner: consul
    group: consul
    mode: 0440
  with_items:
    - dc1-client-consul-0.pem
    - dc1-client-consul-0-key.pem
  no_log: true

- name: Install server certificate and key
  copy:
    src: "etc/consul.d/tls/{{ item }}"
    dest: "/etc/consul.d/tls/{{ item }}"
    owner: consul
    group: consul
    mode: 0400
  with_items:
    - dc1-server-consul-0.pem
    - dc1-server-consul-0-key.pem
  no_log: true
  when: consul_agent_is_server | bool

- name: Create protected directory for ACL tokens
  file:
    path: /etc/consul.d/tokens
    state: directory
    owner: consul
    group: consul
    mode: 0700

- name: Set Consul environment variables
  copy:
    dest: /etc/profile.d/99-consul-env.sh
    mode: 0755
    content: |
      export CONSUL_HTTP_ADDR={{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}
      {% if consul_tls_enabled %}
      export CONSUL_CACERT=/etc/consul.d/tls/consul-agent-ca.pem
      export CONSUL_CLIENT_CERT=/etc/consul.d/tls/dc1-client-consul-0.pem
      export CONSUL_CLIENT_KEY=/etc/consul.d/tls/dc1-client-consul-0-key.pem
      {% endif %}

- name: Configure Consul Configuration
  template:
    src: etc/consul.d/consul.hcl.j2
    dest: '{{consul_config_path}}/consul.hcl'
    owner: '{{consul_user}}'
    group: '{{consul_group}}'
    mode: 0660
  register: consul_config

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_config.changed
