- name: Gather instance metadata
  ec2_metadata_facts:

- name: adding existing user ec2-user to consul and hashi groups
  user:
    name: 'ec2-user'
    groups: consul
    append: yes

- name: Check for master token
  stat:
    path: /etc/consul.d/tokens/master
  register: master_token_file
  ignore_errors: yes

- name: Check for agent token
  stat:
    path: /etc/consul.d/tokens/agent
  register: agent_token_file
  ignore_errors: yes

- name: Check for vault token
  stat:
    path: /etc/consul.d/tokens/vault
  register: vault_token_file
  ignore_errors: yes

- name: Copy file with owner and permissions
  copy:
    src: "cleanup.sh"
    dest: /bin/cleanup
    owner: root
    group: root
    mode: '0750'

- name: Enable TLS if HTTPS port enabled
  set_fact: consul_tls_enabled="{{ (consul_https_port != -1) | ternary(True, False) }}"

- name: Set API endpoint to HTTP or HTTPS
  set_fact:
    consul_api_protocol: "{{ consul_tls_enabled | ternary('https', 'http') }}"
    consul_api_port: "{{ consul_tls_enabled | ternary(consul_https_port, consul_http_port) }}"

- name: Copying Certificates
  import_tasks: certs.yml

- name: Fetch master server token from parameter store
  shell: "aws ssm get-parameter --output json --region {{ ansible_ec2_placement_region }} --with-decryption --name consul_gossip_encryption_key | jq -r '.Parameter | .Value'"
  register: consul_encryption_key
  until: consul_encryption_key.stdout != ""
  retries: 120
  delay: 2
  ignore_errors: yes

- set_fact:
    consul_encryption_key: "{{ consul_encryption_key.stdout }}"

- name: Create protected directory for ACL tokens
  file:
    path: /etc/consul.d/tokens
    state: directory
    owner: consul
    group: consul
    mode: 0700

- name: Set Consul environment variables
  copy:
    dest: /etc/profile.d/99-consul-env.sh
    mode: 0755
    content: |
      export CONSUL_HTTP_ADDR={{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}
      {% if consul_tls_enabled %}
      export CONSUL_CACERT=/etc/consul.d/tls/consul_tls_ca_bundle
      export CONSUL_CLIENT_CERT=/etc/consul.d/tls/consul_client_tls_cert
      export CONSUL_CLIENT_KEY=/etc/consul.d/tls/consul_client_tls_key
      {% endif %}

- name: Configure Consul Configuration
  template:
    src: etc/consul.d/consul.hcl.j2
    dest: '/etc/consul.d/consul.hcl'
    owner: 'consul'
    group: 'consul'
    mode: 0660
  register: consul_config

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_config.changed
