- name: Get Leader Status
  shell: |
    . /etc/profile.d/99-consul-env.sh
    consul info | grep "leader =" | awk '{print $3}'
  register: consul_leader_bool

- name: Set Consul Leader Status
  set_fact: consul_leader="{{ consul_leader_bool.stdout }}"
