- name: Perform Common Tasks
  import_tasks: common.yml

- name: Importing Variables to verify guards against
  import_tasks: import_env.yml

- name: Run leader detection and tasks
  import_tasks: leader.yml
  when:
    - consul_agent_is_server | bool

- debug:
    var: consul_leader

- name: Create Master Token
  import_tasks: token-master.yml
  when:
    - consul_agent_is_server | bool
    - consul_leader == true

- name: Run server agent tasks
  import_tasks: server.yml
  when:
    - consul_agent_is_server | bool

- name: Run leader detection
  import_tasks: leader_status_token.yml
  when:
    - consul_agent_is_server | bool

- name: Run bootstrap tasks
  import_tasks: bootstrap-acl.yml
  when:
    - consul_agent_is_server | bool
    - consul_leader == true
    # - (client_agent_token == "REPLACEME" and vault_agent_token == "REPLACEME")

- name: Write Tokens to File System
  import_tasks: token-write.yml
  when:
    - consul_agent_is_server | bool
    - consul_leader == false

- name: Run client agent tasks
  import_tasks: agent.yml
  when: client_agent_token != "REPLACEME"
