- name: Perform Common Tasks
  import_tasks: common.yml

- name: Run leader detection and tasks
  import_tasks: leader.yml
  when:
    - consul_agent_is_server | bool

- name: Create Master Token
  import_tasks: master-token.yml
  when:
    - consul_leader_bool.stdout == 'true'
    - not master_token_file.stat.exists | bool

- name: Run server agent tasks
  import_tasks: server.yml
  when:
    - consul_agent_is_server | bool

- name: Run leader detection
  import_tasks: leader_status_token.yml
  when:
    - consul_agent_is_server | bool

- name: Run bootstrap tasks
  import_tasks: bootstrap-acl.yml
  when:
    - consul_leader_token_bool.stdout == 'true'
    - consul_agent_is_server | bool

- name: Run client agent tasks
  import_tasks: agent.yml
  when:
    - not (consul_agent_is_server | bool)
