- name: Perform Common Tasks
  import_tasks: common.yml

- name: Run server agent tasks
  import_tasks: server.yml
  when:
    - consul_agent_is_server | bool

- name: Run client agent tasks
  import_tasks: agent.yml
