- debug: msg="START - snapshot.yml"

- name: Create snapshot systemd script
  template:
    src: lib/systemd/system/consul-snapshot-agent.service.j2
    dest: /lib/systemd/system/consul_snapshot.service
    owner: root
    group: root
    mode: 0644
  register: snapshot_service

- name: Create snapshot agent config
  template:
    src: etc/consul.d/consul_snapshot.json.j2
    dest: "{{ consul_config_path }}/consul_snapshot.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: snapshot_service.changed

- name: Create snaps storage folder
  file:
    state: directory
    path: "{{ consul_snapshot_storage }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0744

- debug: msg="END - snapshot.yml"
