- name: Check for agent token on filesystem
  stat: path=/etc/consul.d/tokens/agent
  register: agent_token_file
  ignore_errors: yes

- name: Write Consul agent ACL policy
  set_fact:
    agent_policy: |
      agent_prefix "" {
        policy = "write"
      }
      node_prefix "" {
        policy = "write"
      }
      service_prefix "" {
        policy = "read"
      }

- name: Make Consul agent ACL policy machine-readable
  set_fact:
    agent_policy_api_value: "{{
      agent_policy |
        regex_replace('\n', ' ') |
        regex_replace('\"', '\\\"') |
        regex_replace('\\s+', ' ')
    }}"

- name: Write Consul agent ACL policy to Consul
  uri:
    body_format: json
    body: |
      {
        "Name": "{{ consul_agent_policy_name }}",
        "Description": "Consul agent token",
        "Rules": "{{ agent_policy_api_value }}"
      }
    method: PUT
    url: "{{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}/v1/acl/policy"
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    validate_certs: no
  register: consul_agent_token_write
  run_once: yes

- name: Create agent token
  uri:
    body_format: json
    body: |
      {
        "Description": "Agent token",
        "Policies": [{"Name": "{{ consul_agent_policy_name }}"}],
        "Local": false
      }
    method: PUT
    url: "{{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}/v1/acl/token"
    headers:
      X-Consul-Token: "{{ consul_acl_master_token }}"
    validate_certs: no
    return_content: yes
  register: agent_token
  run_once: yes

- set_fact:
    agent_token: "{{ agent_token.json.SecretID }}"

- name: Show Agent Token - token-agent.yml
  debug:
    var: agent_token

- name: Archive ACL agent token
  copy:
    content: "{{ agent_token }}"
    dest: /etc/consul.d/tokens/agent
    owner: consul
    group: consul
    mode: 0640

- name: Archive ACL agent token to parameter store
  aws_ssm_parameter_store:
    string_type: "SecureString"
    name: "consul-{{ consul_join_tag_value }}-acl-agent"
    value: "{{ agent_token }}"
    description: "Consul Storage Server client agent ACL token"
    region: "{{ ansible_ec2_placement_region }}"
    overwrite_value: "always"
  run_once: yes
