- name: Show Master Key Then write to disk
  debug:
    var: consul_acl_master_token

- name: Archive ACL master token
  copy:
    content: "{{ consul_acl_master_token }}"
    dest: /etc/consul.d/tokens/master
    owner: consul
    group: consul
    mode: 0600

- name: Check for master token on filesystem
  stat:
    path: /etc/consul.d/tokens/master
  register: master_token_file
  ignore_errors: yes
