- name: Import Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install Microsoft Repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ bionic main
    state: present

- name: Install dependencies
  apt:
    name: ['unzip', 'htop', 'jq', 'azure-cli', 'ansible', 'apt-transport-https', 'build-essential', 'python-dev', 'libffi-dev', 'libssl-dev', 'git', 'aptitude']
    state: present
    update_cache: true

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- include: supervisord.yml
