- name: Import EPEL GPG key
  rpm_key:
    key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state: present

- name: Install EPEL 7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install dependencies
  yum:
    name: ['unzip', 'jq', 'awscli', 'ansible']
    state: present
    update_cache: true

- name: "Install Vault Role"
  include_tasks: vault.yml
  when: {{ app }} == 'vault'

- name: "Install Consul Role"
  include_tasks: consul.yml
  when: {{ app }} == 'consul'
