- name: Copy vault archive
  copy:
    src: "vault-enterprise_{{ vault_version }}+prem_linux_amd64.zip"
    dest: "/tmp/vault-enterprise_{{ vault_version }}+prem_linux_amd64.zip"

- name: Unarchive vault
  unarchive:
    src: "/tmp/vault-enterprise_{{ vault_version }}+prem_linux_amd64.zip"
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes

- name: "Copy vault ansible directory"
  copy: src="{{ item }}" dest="/etc/ansible/"
  with_items:
    - "vault-ansible/host_vars"
    - "vault-ansible/roles/consul-agent"
    - "vault-ansible/roles/vault-agent"
    - "vault-ansible/ansible.cfg"
    - "vault-ansible/hosts"
    - "vault-ansible/ec2.ini"
    - "vault-ansible/ec2.py"

- name: Setup autocompletion
  copy:
    content: complete -C "/usr/local/bin/vault" "vault"
    dest: "/etc/profile.d/99-vault-completion.sh"
    mode: 0644

- name: Ensure group "hashi" exists
  group:
    name: hashi
    state: present

- name: Create vault user
  user:
    name: vault
    system: yes
    shell: /bin/false
    home: /etc/vault.d
    createhome: no
    groups: consul
    append: yes
    groups: hashi

- name: Create configuration and TLS directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vault
    group: hashi
    mode: '0740'
  with_items:
    - /etc/vault.d
    - /etc/vault.d/tls

- name: Create data directory
  file:
    path: /var/lib/vault
    state: directory
    owner: vault
    group: vault
    mode: '0700'

- name: Create symbolic link
  file:
    src: "/usr/local/bin/vault"
    dest: "/bin/vault"
    state: link

- name: Install systemd unit
  template:
    src: lib/systemd/system/vault.service.j2
    dest: /lib/systemd/system/vault.service
