- name: Unarchive vault
  unarchive:
    src: "/tmp/vault-enterprise_{{ vault_version }}+prem_linux_amd64.zip"
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: yes

- name: "Copy Vault ansible directory"
  synchronize:
    src: vault/
    dest: "/etc/ansible/"
    recursive: yes
    copy_links: yes

- name: Setup autocompletion
  copy:
    content: complete -C "/usr/local/bin/vault" "vault"
    dest: "/etc/profile.d/99-vault-completion.sh"
    mode: 0644

- name: Ensure group "hashi" exists
  group:
    name: hashi
    state: present

- name: Create vault user
  user:
    name: "{{ vault_user }}"
    system: yes
    shell: /bin/false
    home: "{{ vault_config_path }}"
    createhome: no
    groups: "{{ consul_group }}"
    append: yes

- name: Create configuration and TLS directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ consul_group }}"
    mode: '0740'
  with_items:
    - /etc/vault.d
    - /etc/vault.d/tls

- name: Create data directory
  file:
    path: /var/lib/vault
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0700'

- name: Create symbolic link
  file:
    src: "/usr/local/bin/vault"
    dest: "/bin/vault"
    state: link

- name: Install systemd unit
  template:
    src: vault.service.j2
    dest: /lib/systemd/system/vault.service
