- debug: msg="START - common.yml"

- name: Importing Variables to verify guards against
  import_tasks: import_env.yml

- debug: msg="HTTPS Enabled - {{ consul_https_enabled }}"
  when: debug_verbosity == 1

- name: Enable dnsmasq services
  import_tasks: dns_dnsmasq.yml
  when: consul_dnsmasq | bool

- name: Enable unbound services
  import_tasks: dns_unbound.yml
  when: consul_unbound | bool

- name: adding existing user to consul and hashi groups
  user:
    name: "{{ user }}"
    groups: "{{ consul_group }}"
    append: yes

- name: Copy cleanup script with owner and permissions
  template:
    src: cleanup.sh.j2
    dest: /bin/cleanup
    owner: root
    group: root
    mode: '0750'
    force: yes

- name: Set API endpoint to HTTP or HTTPS
  set_fact:
    consul_api_protocol: "{{ consul_https_enabled | ternary('https', 'http') }}"
    consul_api_port: "{{ consul_https_enabled | ternary(consul_https_port, consul_http_port) }}"

- name: Set Consul environment variables
  copy:
    dest: /etc/profile.d/99-consul-env.sh
    mode: 0755
    content: |
      export CONSUL_HTTP_ADDR={{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}
      {% if consul_https_enabled | bool -%}
      export CONSUL_CACERT={{ consul_config_path }}/tls/consul_tls_ca_bundle
      export CONSUL_CLIENT_CERT={{ consul_config_path }}/tls/consul_client_tls_cert
      export CONSUL_CLIENT_KEY={{ consul_config_path }}/tls/consul_client_tls_key
      {% endif -%}

- debug: msg="END - common.yml"
