- debug: msg="START - common.yml"

- name: Gather instance metadata
  ec2_metadata_facts:

- name: Importing Variables to verify guards against
  import_tasks: import_env.yml

- debug: msg="{{ consul_https_enabled }}"

- name: Copying Certificates
  import_tasks: certs.yml
  when: consul_https_enabled | bool

- name: Enable dnsmasq services
  import_tasks: dns_dnsmasq.yml
  when: consul_dnsmasq | bool

- name: Enable unbound services
  import_tasks: dns_unbound.yml
  when: consul_unbound | bool

- name: adding existing user ec2-user to consul and hashi groups
  user:
    name: 'ec2-user'
    groups: "{{ consul_group }}"
    append: yes

- name: Copy cleanup script with owner and permissions
  template:
    src: cleanup.sh
    dest: /bin/cleanup
    owner: root
    group: root
    mode: '0750'

- name: Create protected directory for ACL tokens
  file:
    path: "{{ consul_config_path }}/tokens"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0700

- name: Enable TLS if HTTPS port enabled
  set_fact: consul_tls_enabled="{{ (consul_https_port != -1) | ternary(True, False) }}"

- name: Set API endpoint to HTTP or HTTPS
  set_fact:
    consul_api_protocol: "{{ consul_tls_enabled | ternary('https', 'http') }}"
    consul_api_port: "{{ consul_tls_enabled | ternary(consul_https_port, consul_http_port) }}"

- name: Set Consul environment variables
  copy:
    dest: /etc/profile.d/99-consul-env.sh
    mode: 0755
    content: |
      export CONSUL_HTTP_ADDR={{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}
      {% if consul_https_enabled | bool -%}
      export CONSUL_CACERT={{ consul_config_path }}/tls/consul_tls_ca_bundle
      export CONSUL_CLIENT_CERT={{ consul_config_path }}/tls/consul_client_tls_cert
      export CONSUL_CLIENT_KEY={{ consul_config_path }}/tls/consul_client_tls_key
      {% endif -%}

- name: Configure Consul Configuration
  template:
    src: etc/consul.d/consul.hcl.j2
    dest: "{{ consul_config_path }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0660
  register: consul_config

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_config.changed

- debug: msg="END - common.yml"
