- name: Consul Configuration
  template:
    src: etc/consul.d/consul.hcl.j2
    dest: "{{ consul_config_path }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0660
  register: consul_config

- name: Additional Configurations
  template:
    src: "etc/consul.d/{{ item }}.hcl.j2"
    dest: "{{ consul_config_path }}/{{ item }}.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0660
  with_items:
    - acl
    - autopilot
    - cluster_version
    - redundancy_zone
  register: additional_config

- name: Restart Consul
  service: name=consul state=restarted
  when: consul_config.changed or additional_config.changed

- name: Wait and check for serf port
  wait_for:
    port: "{{ consul_serf_lan_port }}"
    delay: 6
  when: consul_config.changed or additional_config.changed
