- debug: msg="START - import_env.yml"

- name: register files first
  import_tasks: register-files.yml

- name: Azure ENV Pull
  import_tasks: azure.yml
  when: cloud_env == "azure"

- name: AWS ENV Pull
  import_tasks: aws.yml
  when: cloud_env == "aws"

# if we don't regsiter, the aws import above, even if skipped, blanks all the declarations
- name: register files
  import_tasks: register-files.yml

## Import master and snapshot tokens
- name: Register Server tokens
  set_fact:
    consul_master_token: "{{ lookup('file', master_token_file.stat.path) }}"
    snapshot_token: "{{ lookup('file', snapshot_token_file.stat.path) }}"
  when:
    - consul_agent_is_server | bool

## Import Token and Keys
- name: Register Agent Tokens
  set_fact:
    consul_encryption_key: "{{ lookup('file', gossip_key_file.stat.path) }}"
    client_agent_token: "{{ lookup('file', agent_token_file.stat.path) }}"
    vault_token: "{{ lookup('file', vault_token_file.stat.path) }}"
    default_token: "{{ lookup('file', default_token_file.stat.path) }}"

- name: Debug Output
  import_tasks: debug.yml
  when: debug_verbosity == 1

- debug: msg="END - import_env.yml"
