- name: Get Leader Status
  shell: |
    . /etc/profile.d/99-consul-env.sh
    export CONSUL_HTTP_TOKEN=$(cat /etc/consul.d/tokens/master)
    consul info | grep "leader =" | awk '{print $3}'
  register: consul_leader_token_bool

- name: Set Consul Leader Status
  set_fact: consul_leader="{{ consul_leader_token_bool.stdout }}"

- name: Show Consul Leader - leader_status_token.yml
  debug:
    # verbosity: 2
    var: consul_leader


# - name: Wait for leader
#   uri:
#     method: GET
#     url: https://127.0.0.1:7501/v1/status/leader
#     headers:
#       X-Consul-Token: "{{ consul_acl_tokens.master }}"
#     validate_certs: no
#     return_content: yes
#   register: leader_api
#   failed_when: leader_api.status == 200 and leader_api.content == '""'
#   retries: 75
#   delay: 4
#   until: leader_api.status == 200 and leader_api.content != '""'
# - name: Set fact for known Consul leader
#   set_fact:
#     host_ip_rpc_string: "\"{{ ansible_default_ipv4.address }}:{{ consul_server_rpc_port }}\""
# - name: Set default host_is_leader fact to no
#   set_fact:
#     host_is_leader: no
# - name: Set host_is_leader fact to true if host is leader
#   set_fact:
#     host_is_leader: yes
#   when: leader_api.content is match(host_ip_rpc_string)
