- name: Get Leader Address
  uri:
    method: GET
    url: "{{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}/v1/status/leader"
    validate_certs: no
    return_content: yes
    body_format: json
  register: consul_leader_address
  until: consul_leader_address.json != ""
  retries: 120
  delay: 2
  ignore_errors: yes

- name: Set Consul Leader Address
  set_fact: consul_leader_addr="{{ consul_leader_address.json }}"

- name: Show Consul Leader Address - leader_address.yml
  debug:
    var: consul_leader_addr

- name: Get Leader Status
  shell: |
    . /etc/profile.d/99-consul-env.sh
    export CONSUL_HTTP_TOKEN=$(cat /etc/consul.d/tokens/agent)
    consul info | grep "leader =" | awk '{print $3}'
  register: consul_leader_bool

- name: Set Consul Leader Status
  set_fact: consul_leader="{{ consul_leader_bool.stdout }}"

- name: Show Consul Leader - leader_status_token.yml
  debug:
    # verbosity: 2
    var: consul_leader
