- debug: msg="START - server.yml"

- name: Master Token
  import_tasks: token-master.yml

- name: Run leader detection and tasks
  import_tasks: leader.yml

- name: Show consul leader
  debug:
    var: consul_leader

# - name: Run leader detection
#   import_tasks: leader_status_token.yml

- name: Add ACL configuration - server.yml
  template:
    src: etc/consul.d/acl.hcl.j2
    dest: '/etc/consul.d/acl.hcl'
    owner: 'consul'
    group: 'consul'
    mode: 0660
  register: consul_acl_config

- name: Restart Consul - server.yml
  service: name=consul state=restarted
  when: consul_acl_config.changed

- name: Wait and check for serf port
  wait_for:
    port: "{{ consul_serf_lan_port }}"
    delay: 6

- name: Check for agent token on filesystem
  stat: path=/etc/consul.d/tokens/agent
  register: agent_token_file
  ignore_errors: yes

- name: Check for vault token on filesystem
  stat: path=/etc/consul.d/tokens/vault
  register: vault_token_file
  ignore_errors: yes

- name: Run bootstrap tasks
  import_tasks: bootstrap-acl.yml
  when:
    - consul_leader == true

- name: Write Tokens to File System
  import_tasks: token-write.yml
  when: consul_leader == false

- debug: msg="END - server.yml"
