- name: Fetch Master token from parameter store
  shell: "aws ssm get-parameter --output json --region {{ ansible_ec2_placement_region }} --with-decryption --name consul-{{ consul_join_tag_value }}-acl-master | jq -r '.Parameter | .Value'"
  register: consul_acl_master_token
  until: consul_acl_master_token.stdout != ""
  retries: 120
  delay: 2
  ignore_errors: yes

- name: Register ACL master token for Ansible plays
  set_fact: consul_acl_master_token="{{ consul_acl_master_token.stdout }}"

- name: Show Master Token
  debug:
    var: consul_acl_master_token

- name: Archive ACL master token
  copy:
    content: "{{ consul_acl_master_token }}"
    dest: /etc/consul.d/tokens/master
    owner: consul
    group: consul
    mode: 0600
  when: master_token_file.stat.exists == False
