- name: Write Consul default ACL policy
  set_fact:
    default_policy: |
      node_prefix "" {
        policy = "read"
      }
      service_prefix "" {
        policy = "read"
      }
      session_prefix "" {
        policy = "read"
      }
      agent_prefix "" {
        policy = "read"
      }
      query_prefix "" {
        policy = "read"
      }
      operator = "read"

- name: Make Consul default ACL policy machine-readable
  set_fact:
    default_policy_api_value: "{{
      default_policy |
        regex_replace('\n', ' ') |
        regex_replace('\"', '\\\"') |
        regex_replace('\\s+', ' ')
    }}"

- name: Write Consul default ACL policy to Consul
  uri:
    body_format: json
    body: |
      {
        "Name": "{{ consul_default_policy_name }}",
        "Description": "Consul default token for DNS resolution",
        "Rules": "{{ default_policy_api_value }}"
      }
    method: PUT
    url: "{{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}/v1/acl/policy"
    headers:
      X-Consul-Token: "{{ consul_master_token }}"
    validate_certs: no
  register: consul_default_token_write
  run_once: yes

- name: Write Token
  shell: |
    . /etc/profile.d/99-consul-env.sh
    export CONSUL_HTTP_TOKEN=$(cat /etc/consul.d/tokens/master)
    consul acl token create -description 'Consul agent token' -policy-name "{{ consul_default_policy_name }}" -secret "{{ default_token }}"
  register: consul_default_token_create
