- name: Write vault ACL policy for Vault
  set_fact:
    application_policy: |
      node_prefix "" {
        policy = "write"
      }
      service "vault" {
        policy = "write"
      }
      agent_prefix "" {
        policy = "write"
      }
      key_prefix "vault/" {
        policy = "write"
      }
      session_prefix "" {
        policy = "write"
      }

- name: Make vault ACL policy machine-readable
  set_fact:
    application_policy_api_value: "{{
      application_policy |
        regex_replace('\n', ' ') |
        regex_replace('\"', '\\\"') |
        regex_replace('\\s+', ' ')
    }}"
  when:
    - application_policy is defined

- name: Write vault ACL policy to Consul
  uri:
    body_format: json
    body: |
      {
        "Name": "{{ consul_application_policy_name }}",
        "Description": "Vault token",
        "Rules": "{{ application_policy_api_value }}"
      }
    method: PUT
    url: "{{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}/v1/acl/policy"
    headers:
      X-Consul-Token: "{{ consul_master_token }}"
    validate_certs: no
  register: consul_vault_token_write
  run_once: yes

- name: Write Token
  shell: |
    . /etc/profile.d/99-consul-env.sh
    export CONSUL_HTTP_TOKEN=$(cat /etc/consul.d/tokens/master)
    consul acl token create -description 'Vault token' -policy-name "{{ consul_application_policy_name }}" -secret "{{ vault_token }}"
  register: consul_vault_token_create
