- name: Install CA certificate
  copy:
    content: "{{ consul_tls_ca_bundle.stdout }}"
    dest: /etc/consul.d/tls/consul_tls_ca_bundle
    owner: consul
    group: consul
    mode: 0440
  when: stat_consul_tls_ca_bundle.stat.exists == false
  # no_log: true

- name: Install client certificate
  copy:
    content: "{{ consul_client_tls_cert.stdout }}"
    dest: "/etc/consul.d/tls/consul_client_tls_cert"
    owner: consul
    group: consul
    mode: 0440
  when: stat_consul_client_tls_cert.stat.exists == false
    # no_log: true

- name: Install client certificate key
  copy:
    content: "{{ consul_client_tls_key.stdout }}"
    dest: "{{ consul_config_path }}/tls/consul_client_tls_key"
    owner: consul
    group: consul
    mode: 0440
  when: stat_consul_client_tls_key.stat.exists == false
    # no_log: true
