- debug: msg="START - common.yml"

- name: Check for /etc/consul.d/tls/consul_tls_ca_bundle
  stat: path="{{ consul_config_path }}/tls/consul_tls_ca_bundle"
  register: stat_consul_tls_ca_bundle

- name: Check for /etc/consul.d/tls/consul_client_tls_cert
  stat: path="{{ consul_config_path }}/tls/consul_client_tls_cert"
  register: stat_consul_client_tls_cert

- name: Check for /etc/consul.d/tls/consul_client_tls_key
  stat: path="{{ consul_config_path }}/tls/consul_client_tls_key"
  register: stat_consul_client_tls_key

- name: Check for /etc/consul.d/tls/consul_server_tls_cert
  stat: path="{{ consul_config_path }}/tls/consul_server_tls_cert"
  register: stat_consul_server_tls_cert

- name: Check for /etc/consul.d/tls/consul_server_tls_key
  stat: path="{{ consul_config_path }}/tls/consul_server_tls_key"
  register: stat_consul_server_tls_key

- name: adding existing user sre to consul group
  user:
    name: 'sre'
    groups: "{{ consul_group }}"
    append: yes

- debug: msg="{{ consul_https_enabled }}"
- name: Enable TLS if HTTPS port enabled
  set_fact: consul_tls_enabled="{{ (consul_https_port != -1) | ternary(True, False) }}"

- name: Set API endpoint to HTTP or HTTPS
  set_fact:
    consul_api_protocol: "{{ consul_tls_enabled | ternary('https', 'http') }}"
    consul_api_port: "{{ consul_tls_enabled | ternary(consul_https_port, consul_http_port) }}"

- name: Set Consul environment variables
  copy:
    dest: /etc/profile.d/99-consul-env.sh
    mode: 0755
    content: |
      export CONSUL_HTTP_ADDR={{ consul_api_protocol }}://127.0.0.1:{{ consul_api_port }}
      {% if consul_https_enabled | bool -%}
      export CONSUL_CACERT={{ consul_config_path }}/tls/consul_tls_ca_bundle
      export CONSUL_CLIENT_CERT={{ consul_config_path }}/tls/consul_client_tls_cert
      export CONSUL_CLIENT_KEY={{ consul_config_path }}/tls/consul_client_tls_key
      {% endif -%}

- name: Check for master token on filesystem
  stat: path="{{ consul_config_path }}/tokens/master"
  register: master_token_file

- name: Register ACL Master Agent token for Ansible plays
  set_fact: consul_acl_master_token="{{ lookup('file', master_token_file.stat.path) }}"
  when: master_token_file.stat.exists == true


- debug: msg="END - common.yml"
