- name: Fetch Root Cert from parameter store
  shell: "aws ssm get-parameter --output json --region {{ ansible_ec2_placement_region }} --with-decryption --name vault_tls_ca_bundle | jq -r '.Parameter | .Value'"
  register: vault_tls_ca_bundle
  until: vault_tls_ca_bundle.stdout != ""
  retries: 120
  delay: 2
  ignore_errors: yes
  when: stat_vault_tls_ca_bundle.stat.exists == false

- name: Fetch Server Cert from parameter store
  shell: "aws ssm get-parameter --output json --region {{ ansible_ec2_placement_region }} --with-decryption --name vault_server_tls_cert | jq -r '.Parameter | .Value'"
  register: vault_server_tls_cert
  until: vault_server_tls_cert.stdout != ""
  retries: 120
  delay: 2
  ignore_errors: yes
  when: stat_vault_server_tls_cert.stat.exists == false

- name: Fetch Server Cert Key from parameter store
  shell: "aws ssm get-parameter --output json --region {{ ansible_ec2_placement_region }} --with-decryption --name vault_server_tls_key | jq -r '.Parameter | .Value'"
  register: vault_server_tls_key
  until: vault_server_tls_key.stdout != ""
  retries: 120
  delay: 2
  ignore_errors: yes
  when: stat_vault_server_tls_key.stat.exists == false

- name: Install CA certificate
  copy:
    content: "{{ vault_tls_ca_bundle.stdout }}"
    dest: "{{ stat_vault_tls_ca_bundle.stat.path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0440
  when: stat_vault_tls_ca_bundle.stat.exists == false
  no_log: true

- name: Install server certificate
  copy:
    content: "{{ vault_server_tls_cert.stdout }}"
    dest: "{{ stat_vault_server_tls_cert.stat.path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400
  no_log: true
  when: stat_vault_server_tls_cert.stat.exists == false

- name: Install server certificate key
  copy:
    content: "{{ vault_server_tls_key.stdout }}"
    dest: "{{ stat_vault_server_tls_key.stat.path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0400
  no_log: true
  when: stat_vault_server_tls_key.stat.exists == false
