- debug: msg="START - common.yml"

- name: Importing Variables to verify guards against
  import_tasks: import_env.yml

- debug: msg="HTTPS Enabled - {{ vault_https_enabled }}"
  when: debug_verbosity == 1

- name: adding existing user to consul and hashi groups
  user:
    name: "{{ user }}"
    groups: "{{ consul_group }},{{ vault_group }}"
    append: yes

- name: Copy cleanup script with owner and permissions
  template:
    src: cleanup.sh.j2
    dest: /bin/cleanup
    owner: root
    group: root
    mode: '0750'
    force: yes

- name: Set API endpoint to HTTP or HTTPS
  set_fact:
    vault_api_protocol: "{{ vault_https_enabled | ternary('https', 'http') }}"
    vault_api_port: "{{ vault_https_enabled | ternary(vault_https_port, vault_http_port) }}"

- name: Set Vault environment variables
  copy:
    dest: /etc/profile.d/99-vault-env.sh
    mode: 0755
    content: |
      export VAULT_ADDR={{ vault_api_protocol }}://127.0.0.1:{{ vault_api_port }}
      {% if vault_https_enabled | bool -%}
      export VAULT_CACERT={{ vault_config_path }}/tls/vault_tls_ca_bundle
      export VAULT_CLIENT_CERT={{ vault_config_path }}/tls/vault_server_tls_cert
      export VAULT_CLIENT_KEY={{ vault_config_path }}/tls/vault_server_tls_key
      {% endif -%}

- debug: msg="END - common.yml"
