- name: Perform Common Tasks
  import_tasks: common.yml

- name: Configure Vault
  import_tasks: vault.yml

- name: Unseal Vault
  import_tasks: unseal.yml
  when:
    - vault_unsealed.stat.exists == false
    - vault_unseal == true
