- name: Set Unseal Keys
  set_fact: unseal_keys="{{ lookup('file', tempdir + '/vault_unseal.txt').splitlines() }}"

# - debug: msg="{{ item }} - {{ index }}"
#   loop: "{{ unseal_keys }}"
#   loop_control:
#     index_var: index

- name: Archive shards to parameter store
  aws_ssm_parameter_store:
    string_type: "SecureString"
    name: "vault_recovery_share_{{ index }}"
    value: "{{ item }}"
    description: "Consul Storage Server client agent ACL token"
    region: "{{ ansible_ec2_placement_region }}"
    overwrite_value: "always"
  loop: "{{ unseal_keys }}"
  loop_control:
    index_var: index

# - name: Archive shards to parameter store
#   aws_ssm_parameter_store:
#     string_type: "SecureString"
#     name: "vault_recovery_share_{{ ansible_loop.index }}"
#     value: "{{ item }}"
#     description: "Consul Storage Server client agent ACL token"
#     region: "{{ ansible_ec2_placement_region }}"
#     overwrite_value: "always"
#     loop: "{{ unseal_keys_output }}"
#     loop_control:
#       extended: yes
#   with_lines: "cat {{ unseal_keys_temp_file.stat.path }}"
#   when:
#     - ansible_loop.index <= vault_recovery_shares
