- name: Create protected directory for ACL tokens
  file:
    path: "{{ consul_config_path }}/tokens"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0700

- name: Archive Master token
  copy:
    content: "{{ consul_master_token.stdout }}"
    dest: "{{ consul_config_path }}/tokens/master"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when:
    - consul_agent_is_server | bool
    - master_token_file.stat.exists == false

- name: Archive Gossip Key
  copy:
    content: "{{ consul_encryption_key.stdout }}"
    dest: "{{ consul_config_path }}/tokens/gossipkey"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when:
    - gossip_key_file.stat.exists == false

- name: Archive Client agent token
  copy:
    content: "{{ client_agent_token.stdout }}"
    dest: "{{ consul_config_path }}/tokens/agent"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when: agent_token_file.stat.exists == false

- name: Archive Vault token
  copy:
    content: "{{ vault_token.stdout }}"
    dest: "{{ consul_config_path }}/tokens/vault"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when: vault_token_file.stat.exists == false

- name: Archive default token
  copy:
    content: "{{ default_token.stdout }}"
    dest: "{{ consul_config_path }}/tokens/default"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when: default_token_file.stat.exists == false

- name: Archive snapshot token
  copy:
    content: "{{ snapshot_token.stdout }}"
    dest: "{{ consul_config_path }}/tokens/snapshot"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0640
  when:
    - consul_agent_is_server | bool
    - snapshot_token_file.stat.exists == false
