- name: Show Vault Token
  debug:
    verbosity: "{{ debug_verbosity }}"
    var: consul_https_enabled

- name: Configure Vault Configuration
  template:
    src: etc/vault.d/vault.hcl.j2
    dest: '/etc/vault.d/vault.hcl'
    owner: 'vault'
    group: 'vault'
    mode: 0660
  register: vault_config

- name: Restart Vault
  service: name=vault state=restarted
  when: vault_config.changed
