---
# LogFiles
consul_server_log: "consulserver.log"
consul_agent_log:  "consulagent.log"
#Paths
consul_config_path: "/etc/consul.d"
consul_logs_path:  "/var/log/consul"
consul_bin_path:  "/usr/local/bin"
consul_data_path: "/var/lib/consul"
consul_data_dir: "consuldata"
consul_tls_path: "/etc/pki/certs"
consul_ca_file: "tls-ca-bundle.pem"
consul_cert_file: "iheart-cert.pem"
consul_key_file: "iheart-key.pem"
# Users and Groups
consul_user: "consul"
consul_group: "consul"
#config files
consul_config_file: "consul.json"
consul_start_script: "start-consul.sh"
consul_service: "consul.service"
sysd_svc_path: "/etc/systemd/system/"
consul_node: "ansible_hostname"
# Data Vaules
consul_data_center: "us-east-1"
consul_encryption: "hRxKsBa9CYTW07jjvKXLPg=="
consul_log_level: "info"
consul_redun_zone: "us-east-1"
